apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
{{- if .Values.namespace.enabled }}
  namespace: {{ .Values.namespace.name }}
{{- end }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Chart.Version }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      release: {{ .Chart.Version }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Chart.Name }}
        release: {{ .Chart.Version }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.volumes.secrets.name }}
                  key: key
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.volumes.secrets.name }}
                  key: secret
            - name: BUCKET
              value: {{ .Values.volumes.bucket.name }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
