apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.volumes.secrets.name }}
{{- if .Values.namespace.enabled }}
  namespace: {{ .Values.namespace.name }}
{{- end }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Chart.Version }}
data:
  key: ${{ secrets.RELAY_KEY }}
  secret: ${{ secrets.RELAY_SECRET }}
type: Opaque